### DISCUSSION TITLE
Getting permission denied error

### DISCUSSION THREAD

**Discussion by robinfuller** [snowflakedb/snowflake-cli-action#14] [Q&A] [answered]
Hey there, our team is trying to modernize and we're working on a POC for deploying snowflake objects with actions but we're running into a bit of trouble.

I'm receiving a permission denied error from  config_manager running on ubuntu. I've tried to dig and understand where exactly I'm going wrong with the permissions and haven't had any success yet. Hoping someone on the team can help me understand where I've gone wrong.

```
 #Setup SnowCLI
      - uses: Snowflake-Labs/snowflake-cli-action@v1
        with:
            cli-version: "latest"
            default-config-file-path: "config.toml"
        
        # Use the CLI
      - name: Test version
        run: snow --version    
    
      - name: Configure SnowCLI
        env: 
          SNOWFLAKE_CONNECTIONS_DEV_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        run: |
          cd $GITHUB_WORKSPACE
          echo "[connections]" > my_config.toml
          echo "[connections.dev]" >> my_config.toml
          echo  "account = ${{ env.SNOWFLAKE_CONNECTIONS_DEV_ACCOUNT }}" >> my_config.toml
        #  cat config.toml
        #  echo "account = \"$SNOWFLAKE_CONNECTIONS_DEV_ACCOUNT\"" >> config.toml
          
      - name: Deploy Objects
        env:
          SNOWFLAKE_CONNECTIONS_DEV_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_CONNECTIONS_DEV_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_CONNECTIONS_DEV_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_CONNECTIONS_DEV_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_CONNECTIONS_DEV_WAREHOUSE: ${{ secrets.SNOWFLAKE_WH }}
          SNOWFLAKE_CONNECTIONS_DEV_DATABASE: ${{ secrets.SNOWFLAKE_DB }}
          SNOWFLAKE_CONNECTIONS_DEV_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          sudo chown $USER /home/runner/work/snowflakegittest/snowflakegittest/my_config.toml
          snow --config-file=$GITHUB_WORKSPACE/my_config.toml sql -q "ALTER GIT REPOSITORY snowflake_extensions FETCH"
          snow --config-file=$GITHUB_WORKSPACE/my_config.toml sql -q "EXECUTE IMMEDIATE FROM @snowflake_extensions/branches/main/snowflake_objects/create_table_test.sql"
```

![image](https://github.com/Snowflake-Labs/snowflake-cli-action/assets/72956424/a1388bb0-3515-4a2b-bdf1-a8f5ed3c9dae)
